version: 2
jobs:
  build:
    docker:
      - image: centos:latest
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: pwd
          command: pwd && ls -la

      - run:
          name: hello world
          command: echo 'Hello World'

